version: "3.8"

services:
  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    depends_on:
      - fastapi
