name: Deploy FastAPI to Google Cloud VM

on:
  push:
    branches:
      - main  # Adjust this to match your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      env:
        GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_CLOUD_KEY }}
      run: |
        echo "$GOOGLE_CLOUD_KEY" > gcloud-service-key.json
        gcloud auth activate-service-account --key-file=gcloud-service-key.json
        gcloud config set project hng3-450620
    - name: Deploy FastAPI using SSH
      run: |
        gcloud compute ssh USER@hng3 --project=hng3-450620 --zone=us-central1-a --command "
          cd /home/teminioluwaopemipo/fastapi-book-project &&
          git pull origin main &&
          source /home/teminioluwaopemipo/fastapi-book-project/venv/bin/activate &&
          pip install -r requirements.txt &&
          sudo systemctl restart fastapi.service
        "
