name: Deploy FastAPI to Render

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main  
jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: pytest 

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X POST "https://api.render.com/v1/services/$SERVICE_ID/deploys" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -d ''
      - name: Restart Render Service on Failure
        if: failure()
        run: |
          curl -X POST "https://api.render.com/v1/services/$SERVICE_ID/restart" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer $RENDER_API_KEY"