name: Deploy FastAPI to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_KEY }}

      - name: Set up Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/YOUR_PROJECT_ID/fastapi-repo/fastapi-app:latest .
          docker push us-central1-docker.pkg.dev/YOUR_PROJECT_ID/fastapi-repo/fastapi-app:latest

      - name: Deploy to VM
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $SERVER_USER@$SERVER_IP "
              sudo docker pull us-central1-docker.pkg.dev/YOUR_PROJECT_ID/fastapi-repo/fastapi-app:latest &&
              sudo docker stop fastapi-container || true &&
              sudo docker run -d --name fastapi-container -p 8000:8000 us-central1-docker.pkg.dev/YOUR_PROJECT_ID/fastapi-repo/fastapi-app:latest
          "
